
/*
 * ns3-to-tos-proxy.cc
 *
 *  Created on: Mars 20, 2011
 *      Author: laurynas
 *     Autogenerated on: 2012-03-20
 */
 
#include <iostream>
#include "ns3-to-tos-proxy_auto.h"


Ns3ToTosProxy::Ns3ToTosProxy() {
    m_tos_functions.set_empty_key("empty");
}            

void
Ns3ToTosProxy::addFunction(std::string name, void * pointer){
    m_tos_functions[name]=pointer;

}
          
            
int
Ns3ToTosProxy::sendSendDone(int b , void * c)
{
 	return ((tossendSendDone)m_tos_functions["sendSendDone"])(b , c);
}
void
Ns3ToTosProxy::radioStartDone(int b)
{
 	((tosradioStartDone)m_tos_functions["radioStartDone"])(b);
}
void
Ns3ToTosProxy::setUniqueID(int b)
{
 	((tossetUniqueID)m_tos_functions["setUniqueID"])(b);
}
void
Ns3ToTosProxy::sim_main_start_mote(int b)
{
 	((tossim_main_start_mote)m_tos_functions["sim_main_start_mote"])(b);
}
int
Ns3ToTosProxy::setProxy(int b)
{
 	return ((tossetProxy)m_tos_functions["setProxy"])(b);
}
void
Ns3ToTosProxy::radioStateDone(int b)
{
 	((tosradioStateDone)m_tos_functions["radioStateDone"])(b);
}

Ns3ToTosProxy::~Ns3ToTosProxy() { }
