
/*
 * ns3-to-tos-proxy.h
 *
 *  Created on: Mars 20, 2011
 *      Author: laurynas
 *     Autogenerated on: 2012-03-20
 */
 

#ifndef NS3TOTOSPROXYAUTO_H_
#define NS3TOTOSPROXYAUTO_H_
#include <stdint.h>

#include <string>
#include <google/dense_hash_map>
typedef int(*tossendSendDone)(int,void *); //typedef for tos function sendSendDone(int b , void * c) 
typedef void(*tosradioStartDone)(int); //typedef for tos function radioStartDone(int b) 
typedef void(*tossetUniqueID)(int); //typedef for tos function setUniqueID(int b) 
typedef void(*tossim_main_start_mote)(int); //typedef for tos function sim_main_start_mote(int b) 
typedef int(*tossetProxy)(int); //typedef for tos function setProxy(int b) 
typedef void(*tosradioStateDone)(int); //typedef for tos function radioStateDone(int b) 



using google::dense_hash_map;

class Ns3ToTosProxy {
    public:
        Ns3ToTosProxy();
        void addFunction(std::string name, void * pointer);
		int sendSendDone(int b , void * c);
		void radioStartDone(int b);
		void setUniqueID(int b);
		void sim_main_start_mote(int b);
		int setProxy(int b);
		void radioStateDone(int b);

    ~Ns3ToTosProxy();
private:
    dense_hash_map<std::string, void *> m_tos_functions;

};

#endif /* NS3TOTOSPROXYAUTO_H_ */
