## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    tos_node = bld.create_ns3_module('tos-node')
    tos_node.source = [
        'SimuClock.cc',
        'TosNode.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'tos-node'
    headers.source = [
        'SimuClock.h',
        'TosNode.h',
        ]
