# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tos-simple', ['symphony'])
    obj.source = 'tos.cc'
    obj1 = bld.create_ns3_program('tos-sensor',['symphony'])
    obj1.source = 'tos-sensor.cc'

