## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
#OBS! it is necessary to build your app this way, because of the xerces library
def build(bld):
    obj = bld.create_ns3_program('tos-simple',
                                 ['tos'])
    
    obj.env.append_value('LINKFLAGS','-lxerces-c')
    obj.source = 'tos.cc'



