## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('tos-simple',
                                 ['tos'])
    obj.env.append_value('LINKFLAGS','-lxerces-c')
    obj.source = 'tos.cc'



