/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'RadioCountMsg'
 * message type.
 */

public class RadioCountMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 121;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new RadioCountMsg of size 121. */
    public RadioCountMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new RadioCountMsg of the given data_length. */
    public RadioCountMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg with the given data_length
     * and base offset.
     */
    public RadioCountMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store.
     */
    public RadioCountMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public RadioCountMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public RadioCountMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new RadioCountMsg embedded in the given message
     * at the given base offset and length.
     */
    public RadioCountMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <RadioCountMsg> \n";
      try {
        s += "  [counter=";
        for (int i = 0; i < 121; i++) {
          s += "0x"+Long.toHexString(getElement_counter(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: counter
    //   Field type: short[], unsigned
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'counter' is signed (false).
     */
    public static boolean isSigned_counter() {
        return false;
    }

    /**
     * Return whether the field 'counter' is an array (true).
     */
    public static boolean isArray_counter() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'counter'
     */
    public static int offset_counter(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 121) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'counter'
     */
    public static int offsetBits_counter(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 121) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'counter' as a short[]
     */
    public short[] get_counter() {
        short[] tmp = new short[121];
        for (int index0 = 0; index0 < numElements_counter(0); index0++) {
            tmp[index0] = getElement_counter(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'counter' from the given short[]
     */
    public void set_counter(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_counter(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'counter'
     */
    public short getElement_counter(int index1) {
        return (short)getUIntBEElement(offsetBits_counter(index1), 8);
    }

    /**
     * Set an element of the array 'counter'
     */
    public void setElement_counter(int index1, short value) {
        setUIntBEElement(offsetBits_counter(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'counter'
     */
    public static int totalSize_counter() {
        return (968 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'counter'
     */
    public static int totalSizeBits_counter() {
        return 968;
    }

    /**
     * Return the size, in bytes, of each element of the array 'counter'
     */
    public static int elementSize_counter() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'counter'
     */
    public static int elementSizeBits_counter() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'counter'
     */
    public static int numDimensions_counter() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'counter'
     */
    public static int numElements_counter() {
        return 121;
    }

    /**
     * Return the number of elements in the array 'counter'
     * for the given dimension.
     */
    public static int numElements_counter(int dimension) {
      int array_dims[] = { 121,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'counter' with a String
     */
    public void setString_counter(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_counter(i, (short)s.charAt(i));
         }
         setElement_counter(i, (short)0); //null terminate
    }

    /**
     * Read the array 'counter' as a String
     */
    public String getString_counter() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,121)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_counter(i) == (char)0) break;
             carr[i] = (char)getElement_counter(i);
         }
         return new String(carr,0,i);
    }

}
