#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'RadioCountMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 121

# The Active Message type associated with this message.
AM_TYPE = 6

class RadioCountMsg(tinyos.message.Message.Message):
    # Create a new RadioCountMsg of size 121.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=121):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <RadioCountMsg> \n"
        try:
            s += "  [counter=";
            for i in range(0, 121):
                s += "0x%x " % (self.getElement_counter(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: short[]
    #   Offset (bits): 0
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (True).
    #
    def isArray_counter(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 121:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self, index1):
        offset = 0
        if index1 < 0 or index1 >= 121:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'counter' as a short[]
    #
    def get_counter(self):
        tmp = [None]*121
        for index0 in range (0, self.numElements_counter(0)):
                tmp[index0] = self.getElement_counter(index0)
        return tmp
    
    #
    # Set the contents of the array 'counter' from the given short[]
    #
    def set_counter(self, value):
        for index0 in range(0, len(value)):
            self.setElement_counter(index0, value[index0])

    #
    # Return an element (as a short) of the array 'counter'
    #
    def getElement_counter(self, index1):
        return self.getUIntElement(self.offsetBits_counter(index1), 8, 1)
    
    #
    # Set an element of the array 'counter'
    #
    def setElement_counter(self, index1, value):
        self.setUIntElement(self.offsetBits_counter(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'counter'
    #
    def totalSize_counter(self):
        return (968 / 8)
    
    #
    # Return the total size, in bits, of the array 'counter'
    #
    def totalSizeBits_counter(self):
        return 968
    
    #
    # Return the size, in bytes, of each element of the array 'counter'
    #
    def elementSize_counter(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'counter'
    #
    def elementSizeBits_counter(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'counter'
    #
    def numDimensions_counter(self):
        return 1
    
    #
    # Return the number of elements in the array 'counter'
    #
    def numElements_counter():
        return 121
    
    #
    # Return the number of elements in the array 'counter'
    # for the given dimension.
    #
    def numElements_counter(self, dimension):
        array_dims = [ 121,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'counter' with a String
    #
    def setString_counter(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_counter(i, ord(s[i]));
         self.setElement_counter(l, 0) #null terminate
    
    #
    # Read the array 'counter' as a String
    #
    def getString_counter(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_counter(i) == chr(0):
                break
            carr += self.getElement_counter(i)
        return carr
    
