
/*
 * ns3-to-tos-proxy.cc
 *
 *  Created on: Mars 20, 2011
 *      Author: laurynas
 *     Autogenerated on: 2013-08-28
 */
 
#include <iostream>
#include "ns3-to-tos-proxy_auto.h"


Ns3ToTosProxy::Ns3ToTosProxy() {
    //m_tos_functions.set_empty_key("empty");
}            

void
Ns3ToTosProxy::addFunction(std::string name, void * pointer){
    m_tos_functions[name]=pointer;

}
          
            
int
Ns3ToTosProxy::sendDone(void * b , uint8_t c)
{
 	return ((tossendDone)m_tos_functions["sendDone"])(b , c);
}
void
Ns3ToTosProxy::radioStartDone(int b)
{
 	((tosradioStartDone)m_tos_functions["radioStartDone"])(b);
}
int
Ns3ToTosProxy::setUniqueID(int b)
{
 	return ((tossetUniqueID)m_tos_functions["setUniqueID"])(b);
}
void
Ns3ToTosProxy::sim_main_start_mote(int b)
{
 	((tossim_main_start_mote)m_tos_functions["sim_main_start_mote"])(b);
}
int
Ns3ToTosProxy::setProxy(long b)
{
 	return ((tossetProxy)m_tos_functions["setProxy"])(b);
}
int
Ns3ToTosProxy::tickFired(uint32_t b)
{
 	return ((tostickFired)m_tos_functions["tickFired"])(b);
}
int
Ns3ToTosProxy::radioStateDone()
{
 	return ((tosradioStateDone)m_tos_functions["radioStateDone"])();
}
int
Ns3ToTosProxy::receiveMessage(void * b)
{
 	return ((tosreceiveMessage)m_tos_functions["receiveMessage"])(b);
}
int
Ns3ToTosProxy::runNextEventExternal(uint32_t b)
{
 	return ((tosrunNextEventExternal)m_tos_functions["runNextEventExternal"])(b);
}
int
Ns3ToTosProxy::sensorStartDone(uint8_t b)
{
 	return ((tossensorStartDone)m_tos_functions["sensorStartDone"])(b);
}
int
Ns3ToTosProxy::sensorStopDone(uint8_t b)
{
 	return ((tossensorStopDone)m_tos_functions["sensorStopDone"])(b);
}
int
Ns3ToTosProxy::interruptData(uint8_t b , uint16_t c , void * d)
{
 	return ((tosinterruptData)m_tos_functions["interruptData"])(b , c , d);
}
int
Ns3ToTosProxy::InitializationVectorInterrupt(uint8_t b , uint16_t c , void * d)
{
 	return ((tosInitializationVectorInterrupt)m_tos_functions["InitializationVectorInterrupt"])(b , c , d);
}
int
Ns3ToTosProxy::RandomVectorInterrupt(uint8_t b , uint16_t c , void * d)
{
 	return ((tosRandomVectorInterrupt)m_tos_functions["RandomVectorInterrupt"])(b , c , d);
}
int
Ns3ToTosProxy::actuatorInterrupt(uint8_t b , uint16_t c , void * d)
{
 	return ((tosactuatorInterrupt)m_tos_functions["actuatorInterrupt"])(b , c , d);
}
int
Ns3ToTosProxy::actuatorHvInterrupt(uint8_t b , uint16_t c , void * d)
{
 	return ((tosactuatorHvInterrupt)m_tos_functions["actuatorHvInterrupt"])(b , c , d);
}
void
Ns3ToTosProxy::ApplicationStartDone(uint8_t b)
{
 	((tosApplicationStartDone)m_tos_functions["ApplicationStartDone"])(b);
}
void
Ns3ToTosProxy::AplicationStopDone(uint8_t b)
{
 	((tosAplicationStopDone)m_tos_functions["AplicationStopDone"])(b);
}
void* 
Ns3ToTosProxy::getFunction(std::string name){
	return (void *)m_tos_functions[name]; 
}
Ns3ToTosProxy::~Ns3ToTosProxy() { }
