## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
  tos_bridge = bld.create_ns3_module('tos-bridge')
  tos_bridge.source = [
        'LibToTosProxy.cc',
        'TosToLibProxy.cc',
        'TinyBridge.cc',
        ]

  headers = bld.new_task_gen('ns3header')
  headers.module = 'tos-bridge'
  headers = [
        'gateway.h',
        'LibToTosProxy.h',
        'TosToLibProxy.h',
        'TinyBridge.h',
        ]
