## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
  print "build symphony"
  symphony = bld.create_ns3_module('symphony')
  symphony.source = [
        'symphony.cc']


  headers = bld.new_task_gen('ns3header')
  headers.module = 'symphony'
  headers = [
        'tos-bridge/gateway.h',
        'tos-bridge/LibToTosProxy.h',
        'tos-bridge/TosToLibProxy.h',
        'tos-bridge/TinyBridge.h',
        'tos-node/SimuClock.h',
        'tos-node/TosNode.h',
        'symphony.h'
        ]
  #print dir(headers)
