## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    tos_node = bld.create_ns3_module('helpers')
    tos_node.source = [
        'tos-node-list.cc',
        'tos-node-container.cc',
        
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'helpers'
    headers.source = [
        'tos-node-container.h',
        'tos-node-list.h',
        ]
